# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\LearningCode\Git code\SelfLearning\Personal projects\MyApp\horizontal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyApp(object):
    def setupUi(self, MyApp):
        MyApp.setObjectName("MyApp")
        MyApp.resize(1500, 850)
        self.centralwidget = QtWidgets.QWidget(MyApp)
        self.centralwidget.setStyleSheet("#frame\n"
"{\n"
"    background-color: #164863;\n"
"    border-radius: 25;\n"
"    border: 0\n"
"}\n"
"#frame_usual_app\n"
"{\n"
"    background-color: #4FC1E9;\n"
"    border-radius: 20\n"
"}\n"
"\n"
"#frame_Enter_app {\n"
"    border: 0px solid gray;\n"
"    border-radius: 20px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"#frame_coding_app\n"
"{    \n"
"    border: 0px solid gray;\n"
"    border-radius: 20px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"#ZaloButton\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"#ZaloButton::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#ZaloButton::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}\n"
"\n"
"#YoutubeButton\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"#YoutubeButton::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#YoutubeButton::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}\n"
"\n"
"#FacebookButton\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"#FacebookButton::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#FacebookButton::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}\n"
"\n"
"#VSCodeButton\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"#VSCodeButton::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#VSCodeButton::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}\n"
"\n"
"#GithubButton\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"#GithubButton::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#GithubButton::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}\n"
"\n"
"#GoogleButton\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"#GoogleButton::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#GoogleButton::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}\n"
"\n"
"#frame_day_time{\n"
"    background-color: #F6F6F6;\n"
"    border-image: url(:/Icon/Image/backgroundcalendar.jpg) 0 0 0 0 stretch stretch;\n"
"    border-radius: 15;\n"
"    border: 3px solid #EEEEEE;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(5, 5, 1300, 750))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_usual_app = QtWidgets.QFrame(self.frame)
        self.frame_usual_app.setGeometry(QtCore.QRect(10, 10, 131, 730))
        self.frame_usual_app.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_usual_app.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_usual_app.setObjectName("frame_usual_app")
        self.frame_coding_app = QtWidgets.QFrame(self.frame_usual_app)
        self.frame_coding_app.setGeometry(QtCore.QRect(9, 430, 111, 141))
        self.frame_coding_app.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_coding_app.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_coding_app.setObjectName("frame_coding_app")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_coding_app)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.VSCodeButton = QtWidgets.QPushButton(self.frame_coding_app)
        self.VSCodeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/IconApplication/Image/vscode.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.VSCodeButton.setIcon(icon)
        self.VSCodeButton.setIconSize(QtCore.QSize(50, 50))
        self.VSCodeButton.setObjectName("VSCodeButton")
        self.verticalLayout_3.addWidget(self.VSCodeButton)
        self.GithubButton = QtWidgets.QPushButton(self.frame_coding_app)
        self.GithubButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/IconApplication/Image/github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.GithubButton.setIcon(icon1)
        self.GithubButton.setIconSize(QtCore.QSize(50, 50))
        self.GithubButton.setObjectName("GithubButton")
        self.verticalLayout_3.addWidget(self.GithubButton)
        self.frame_Enter_app = QtWidgets.QFrame(self.frame_usual_app)
        self.frame_Enter_app.setGeometry(QtCore.QRect(10, 160, 111, 261))
        self.frame_Enter_app.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Enter_app.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Enter_app.setObjectName("frame_Enter_app")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_Enter_app)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ZaloButton = QtWidgets.QPushButton(self.frame_Enter_app)
        self.ZaloButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/IconApplication/Image/zalo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ZaloButton.setIcon(icon2)
        self.ZaloButton.setIconSize(QtCore.QSize(50, 50))
        self.ZaloButton.setObjectName("ZaloButton")
        self.verticalLayout_2.addWidget(self.ZaloButton)
        self.YoutubeButton = QtWidgets.QPushButton(self.frame_Enter_app)
        self.YoutubeButton.setEnabled(True)
        self.YoutubeButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/IconApplication/Image/youtube.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.YoutubeButton.setIcon(icon3)
        self.YoutubeButton.setIconSize(QtCore.QSize(50, 47))
        self.YoutubeButton.setObjectName("YoutubeButton")
        self.verticalLayout_2.addWidget(self.YoutubeButton)
        self.FacebookButton = QtWidgets.QPushButton(self.frame_Enter_app)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(11)
        font.setBold(True)
        self.FacebookButton.setFont(font)
        self.FacebookButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/IconApplication/Image/facebook.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FacebookButton.setIcon(icon4)
        self.FacebookButton.setIconSize(QtCore.QSize(48, 48))
        self.FacebookButton.setObjectName("FacebookButton")
        self.verticalLayout_2.addWidget(self.FacebookButton)
        self.GoogleButton = QtWidgets.QPushButton(self.frame_Enter_app)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(11)
        font.setBold(True)
        self.GoogleButton.setFont(font)
        self.GoogleButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/IconApplication/Image/icons8-google-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.GoogleButton.setIcon(icon5)
        self.GoogleButton.setIconSize(QtCore.QSize(48, 48))
        self.GoogleButton.setObjectName("GoogleButton")
        self.verticalLayout_2.addWidget(self.GoogleButton)
        self.frame_info = QtWidgets.QFrame(self.frame_usual_app)
        self.frame_info.setGeometry(QtCore.QRect(10, 630, 111, 45))
        self.frame_info.setStyleSheet("#frame_info{\n"
"    background-color: white;\n"
"    border-radius: 15;\n"
"    border: 1px solid white;\n"
"}")
        self.frame_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_info.setObjectName("frame_info")
        self.label_9 = QtWidgets.QLabel(self.frame_info)
        self.label_9.setGeometry(QtCore.QRect(15, 7, 31, 31))
        self.label_9.setStyleSheet("#label_9\n"
"{\n"
"    border-image: url(:/Icon/Image/Icon.jpg) 0 0 0 0 stretch stretch;\n"
"    border-radius: 15px;\n"
"    border: 1pxsolid white;\n"
"}")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_info)
        self.label_10.setGeometry(QtCore.QRect(50, 3, 51, 41))
        font = QtGui.QFont()
        font.setFamily("SamsungOne 700")
        font.setPointSize(10)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.frame_password_2 = QtWidgets.QFrame(self.frame_usual_app)
        self.frame_password_2.setGeometry(QtCore.QRect(10, 680, 111, 41))
        self.frame_password_2.setStyleSheet("#frame_password_2{\n"
"    background-color: white;\n"
"    border-radius: 15;\n"
"    border: 1px solid white;\n"
"}")
        self.frame_password_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_password_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_password_2.setObjectName("frame_password_2")
        self.pushButton_menu = QtWidgets.QPushButton(self.frame_password_2)
        self.pushButton_menu.setGeometry(QtCore.QRect(15, 5, 30, 30))
        self.pushButton_menu.setStyleSheet("#pushButton_menu\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}\n"
"#pushButton_menu::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_menu::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}")
        self.pushButton_menu.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icon/Image/icons8-menu-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_menu.setIcon(icon6)
        self.pushButton_menu.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_menu.setObjectName("pushButton_menu")
        self.pushButton_login = QtWidgets.QPushButton(self.frame_password_2)
        self.pushButton_login.setGeometry(QtCore.QRect(70, 5, 30, 30))
        self.pushButton_login.setStyleSheet("#pushButton_login\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"#pushButton_login::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_login::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}")
        self.pushButton_login.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icon/Image/icons8-login-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_login.setIcon(icon7)
        self.pushButton_login.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_login.setObjectName("pushButton_login")
        self.frame_password = QtWidgets.QFrame(self.frame_usual_app)
        self.frame_password.setGeometry(QtCore.QRect(10, 580, 111, 45))
        self.frame_password.setStyleSheet("#frame_password{\n"
"    background-color: white;\n"
"    border-radius: 15;\n"
"    border: 1px solid white;\n"
"}")
        self.frame_password.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_password.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_password.setObjectName("frame_password")
        self.pushButton_Plus_pass = QtWidgets.QPushButton(self.frame_password)
        self.pushButton_Plus_pass.setGeometry(QtCore.QRect(70, 8, 28, 28))
        font = QtGui.QFont()
        font.setFamily("SamsungOne 400")
        font.setPointSize(22)
        font.setBold(False)
        self.pushButton_Plus_pass.setFont(font)
        self.pushButton_Plus_pass.setStyleSheet("#pushButton_Plus_pass\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: #5CB8E4;\n"
"    border-radius: 14px;\n"
"    color: white\n"
"}\n"
"#pushButton_Plus_pass::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_Plus_pass::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}")
        self.pushButton_Plus_pass.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Plus_pass.setObjectName("pushButton_Plus_pass")
        self.pushButton_password = QtWidgets.QPushButton(self.frame_password)
        self.pushButton_password.setGeometry(QtCore.QRect(15, 7, 30, 30))
        self.pushButton_password.setStyleSheet("#pushButton_password\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}\n"
"#pushButton_password::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_password::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}")
        self.pushButton_password.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icon/Image/icons8-password-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_password.setIcon(icon8)
        self.pushButton_password.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_password.setObjectName("pushButton_password")
        self.frame_day_time = QtWidgets.QFrame(self.frame_usual_app)
        self.frame_day_time.setGeometry(QtCore.QRect(10, 10, 111, 141))
        self.frame_day_time.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_day_time.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_day_time.setObjectName("frame_day_time")
        self.label_time = QtWidgets.QLabel(self.frame_day_time)
        self.label_time.setGeometry(QtCore.QRect(15, 95, 87, 35))
        font = QtGui.QFont()
        font.setFamily("SamsungOne 400")
        font.setPointSize(25)
        font.setBold(False)
        self.label_time.setFont(font)
        self.label_time.setStyleSheet("color: #3085C3")
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.label_thu = QtWidgets.QLabel(self.frame_day_time)
        self.label_thu.setGeometry(QtCore.QRect(15, 5, 85, 28))
        font = QtGui.QFont()
        font.setFamily("SamsungOne 700")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_thu.setFont(font)
        self.label_thu.setStyleSheet("color: #3085C3")
        self.label_thu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_thu.setObjectName("label_thu")
        self.label_sun = QtWidgets.QLabel(self.frame_day_time)
        self.label_sun.setGeometry(QtCore.QRect(75, 35, 21, 21))
        self.label_sun.setStyleSheet("border-radius: 5px")
        self.label_sun.setText("")
        self.label_sun.setScaledContents(True)
        self.label_sun.setObjectName("label_sun")
        self.label_night = QtWidgets.QLabel(self.frame_day_time)
        self.label_night.setGeometry(QtCore.QRect(75, 75, 21, 21))
        self.label_night.setStyleSheet("border-radius: 5px")
        self.label_night.setText("")
        self.label_night.setScaledContents(True)
        self.label_night.setObjectName("label_night")
        self.label_day = QtWidgets.QLabel(self.frame_day_time)
        self.label_day.setGeometry(QtCore.QRect(25, 37, 60, 55))
        font = QtGui.QFont()
        font.setFamily("SamsungOne 700")
        font.setPointSize(32)
        font.setBold(True)
        self.label_day.setFont(font)
        self.label_day.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_day.setAutoFillBackground(False)
        self.label_day.setStyleSheet("color: #3085C3;\n"
"/*#F6F078*/\n"
"background-color:  #CBBCF6;\n"
"border-radius: 25px")
        self.label_day.setAlignment(QtCore.Qt.AlignCenter)
        self.label_day.setObjectName("label_day")
        self.frame_Image = QtWidgets.QFrame(self.frame)
        self.frame_Image.setGeometry(QtCore.QRect(150, 10, 551, 351))
        self.frame_Image.setStyleSheet("#frame_Image{\n"
"    background-color: white;\n"
"    border-radius: 15;\n"
"    border: 1px solid white;\n"
"}")
        self.frame_Image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Image.setObjectName("frame_Image")
        self.frame_2 = QtWidgets.QFrame(self.frame_Image)
        self.frame_2.setGeometry(QtCore.QRect(10, 5, 531, 341))
        self.frame_2.setStyleSheet("background-color: #5CB8E4;\n"
"border-radius: 20px")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_image = QtWidgets.QLabel(self.frame_2)
        self.label_image.setEnabled(True)
        self.label_image.setGeometry(QtCore.QRect(120, 5, 521, 331))
        self.label_image.setStyleSheet("#label_image\n"
"{\n"
"    border-image: url(:/ImagePersonal/Image/ImagePersonal/1.jpg) 0 0 0 0 stretch stretch;\n"
"    border-radius: 15px;\n"
"    border: 1pxsolid white;\n"
"}")
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.label_image_2 = QtWidgets.QLabel(self.frame_2)
        self.label_image_2.setGeometry(QtCore.QRect(5, 5, 521, 331))
        self.label_image_2.setStyleSheet("#label_image_2\n"
"{\n"
"    border-image: url(:/ImagePersonal/Image/ImagePersonal/11.jpg) 0 0 0 0 stretch stretch;\n"
"    border-radius: 15px;\n"
"    border: 1pxsolid white;\n"
"}")
        self.label_image_2.setText("")
        self.label_image_2.setObjectName("label_image_2")
        self.label_image_2.raise_()
        self.label_image.raise_()
        self.frame_thuchi = QtWidgets.QFrame(self.frame)
        self.frame_thuchi.setGeometry(QtCore.QRect(710, 10, 581, 731))
        self.frame_thuchi.setStyleSheet("#frame_thuchi{\n"
"    background-color: white;\n"
"    border-radius: 15;\n"
"    border: 1px solid white;\n"
"}")
        self.frame_thuchi.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_thuchi.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_thuchi.setObjectName("frame_thuchi")
        self.frame_thu = QtWidgets.QFrame(self.frame_thuchi)
        self.frame_thu.setGeometry(QtCore.QRect(7, 50, 561, 311))
        self.frame_thu.setStyleSheet("#frame_thu{\n"
"    background-color: #8ECDDD;\n"
"    border-radius: 15;\n"
"    border: 1px solid white;\n"
"}")
        self.frame_thu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_thu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_thu.setObjectName("frame_thu")
        self.pushButton_Plus_thu = QtWidgets.QPushButton(self.frame_thu)
        self.pushButton_Plus_thu.setGeometry(QtCore.QRect(5, 275, 31, 31))
        font = QtGui.QFont()
        font.setFamily("SamsungOne 400")
        font.setPointSize(22)
        font.setBold(False)
        self.pushButton_Plus_thu.setFont(font)
        self.pushButton_Plus_thu.setStyleSheet("#pushButton_Plus_thu\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: #5CB8E4;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"#pushButton_Plus_thu::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_Plus_thu::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}")
        self.pushButton_Plus_thu.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Plus_thu.setObjectName("pushButton_Plus_thu")
        self.label_total_thu = QtWidgets.QLabel(self.frame_thu)
        self.label_total_thu.setGeometry(QtCore.QRect(40, 280, 151, 25))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.label_total_thu.setFont(font)
        self.label_total_thu.setStyleSheet("#label_total_thu{\n"
"    background-color: #3085C3;\n"
"    border-radius: 10;\n"
"    border: 1px solid white;\n"
"    color: white\n"
"}")
        self.label_total_thu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_total_thu.setObjectName("label_total_thu")
        self.frametest = QtWidgets.QFrame(self.frame_thu)
        self.frametest.setGeometry(QtCore.QRect(30, 120, 190, 150))
        self.frametest.setStyleSheet("#frametest{\n"
"    background-color: #EDE4E0;\n"
"    border-radius: 15;\n"
"    border: 2px solid white;\n"
"}")
        self.frametest.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frametest.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frametest.setObjectName("frametest")
        self.comboBox = QtWidgets.QComboBox(self.frametest)
        self.comboBox.setGeometry(QtCore.QRect(45, 10, 132, 28))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.comboBox.setFont(font)
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    min-width: 6em;\n"
"    padding-left: 10;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background: transparent;\n"
"    border: 1px solid gray;\n"
"    padding: 4px 4px 4px 4px\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    image: url(\":/Icon/Image/icons8-down-25.png\");\n"
"    width:20;\n"
"    padding-left: 5\n"
"}\n"
"")
        self.comboBox.setEditable(False)
        self.comboBox.setMaxVisibleItems(10)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.frametest)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(45, 80, 131, 28))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setBold(True)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setStyleSheet("border-radius: 10;\n"
"background-color: white;\n"
"border: 1px solid gray;\n"
"padding-left: 5")
        self.plainTextEdit_2.setPlainText("")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_11 = QtWidgets.QLabel(self.frametest)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 25, 25))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/Icon/Image/icons8-goal-40.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frametest)
        self.label_12.setGeometry(QtCore.QRect(10, 45, 25, 25))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/Icon/Image/icons8-money-40.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frametest)
        self.label_13.setGeometry(QtCore.QRect(10, 80, 25, 25))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/Icon/Image/icons8-note-40.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label = QtWidgets.QLabel(self.frametest)
        self.label.setGeometry(QtCore.QRect(140, 50, 35, 20))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_SetThu = QtWidgets.QPushButton(self.frametest)
        self.pushButton_SetThu.setGeometry(QtCore.QRect(60, 115, 71, 25))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton_SetThu.setFont(font)
        self.pushButton_SetThu.setStyleSheet("#pushButton_SetThu\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"#pushButton_SetThu::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_SetThu::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icon/Image/icons8-next-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_SetThu.setIcon(icon9)
        self.pushButton_SetThu.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_SetThu.setObjectName("pushButton_SetThu")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.frametest)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(45, 45, 91, 28))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setStyleSheet("border-radius: 10;\n"
"background-color: white;\n"
"border: 1px solid gray;\n"
"padding-left: 8")
        self.plainTextEdit_3.setPlainText("")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.frame_chi = QtWidgets.QFrame(self.frame_thuchi)
        self.frame_chi.setGeometry(QtCore.QRect(10, 370, 561, 351))
        self.frame_chi.setStyleSheet("#frame_chi{\n"
"    background-color: #FFE3BB;\n"
"    border-radius: 15;\n"
"    border: 1px solid white;\n"
"}")
        self.frame_chi.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_chi.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_chi.setObjectName("frame_chi")
        self.pushButton_Plus_chi = QtWidgets.QPushButton(self.frame_chi)
        self.pushButton_Plus_chi.setGeometry(QtCore.QRect(5, 310, 31, 31))
        font = QtGui.QFont()
        font.setFamily("SamsungOne 400")
        font.setPointSize(22)
        self.pushButton_Plus_chi.setFont(font)
        self.pushButton_Plus_chi.setStyleSheet("#pushButton_Plus_chi\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: #F5A962;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"#pushButton_Plus_chi::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_Plus_chi::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}")
        self.pushButton_Plus_chi.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Plus_chi.setObjectName("pushButton_Plus_chi")
        self.label_6 = QtWidgets.QLabel(self.frame_chi)
        self.label_6.setGeometry(QtCore.QRect(530, 5, 28, 28))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/Icon/Image/icons8-money-48.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_total_chi = QtWidgets.QLabel(self.frame_chi)
        self.label_total_chi.setGeometry(QtCore.QRect(40, 315, 151, 25))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.label_total_chi.setFont(font)
        self.label_total_chi.setStyleSheet("#label_total_chi{\n"
"    background-color: #F5A962;\n"
"    border-radius: 10;\n"
"    border: 1px solid white;\n"
"    color: white\n"
"}")
        self.label_total_chi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_total_chi.setObjectName("label_total_chi")
        self.PopupChi = QtWidgets.QFrame(self.frame_chi)
        self.PopupChi.setGeometry(QtCore.QRect(30, 150, 190, 150))
        self.PopupChi.setStyleSheet("#PopupChi{\n"
"    background-color: #EDE4E0;\n"
"    border-radius: 15;\n"
"    border: 2px solid white;\n"
"}")
        self.PopupChi.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PopupChi.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PopupChi.setObjectName("PopupChi")
        self.comboBox_2 = QtWidgets.QComboBox(self.PopupChi)
        self.comboBox_2.setGeometry(QtCore.QRect(45, 10, 132, 28))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_2.setAutoFillBackground(False)
        self.comboBox_2.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    min-width: 6em;\n"
"    padding-left: 10;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background: transparent;\n"
"    border: 1px solid gray;\n"
"    padding: 4px 4px 4px 4px\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    image: url(\":/Icon/Image/icons8-down-25.png\");\n"
"    width:20;\n"
"    padding-left: 5\n"
"}\n"
"")
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setMaxVisibleItems(10)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.PopupChi)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(45, 80, 131, 28))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setBold(True)
        self.plainTextEdit_4.setFont(font)
        self.plainTextEdit_4.setStyleSheet("border-radius: 10;\n"
"background-color: white;\n"
"border: 1px solid gray;\n"
"padding-left: 5")
        self.plainTextEdit_4.setPlainText("")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.label_14 = QtWidgets.QLabel(self.PopupChi)
        self.label_14.setGeometry(QtCore.QRect(10, 10, 25, 25))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/Icon/Image/icons8-goal-40.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.PopupChi)
        self.label_15.setGeometry(QtCore.QRect(10, 45, 25, 25))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/Icon/Image/icons8-money-40.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.PopupChi)
        self.label_16.setGeometry(QtCore.QRect(10, 80, 25, 25))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(":/Icon/Image/icons8-note-40.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_2 = QtWidgets.QLabel(self.PopupChi)
        self.label_2.setGeometry(QtCore.QRect(140, 50, 35, 20))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_SetChi = QtWidgets.QPushButton(self.PopupChi)
        self.pushButton_SetChi.setGeometry(QtCore.QRect(60, 115, 71, 25))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton_SetChi.setFont(font)
        self.pushButton_SetChi.setStyleSheet("#pushButton_SetChi\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"#pushButton_SetChi::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_SetChi::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}")
        self.pushButton_SetChi.setIcon(icon9)
        self.pushButton_SetChi.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_SetChi.setObjectName("pushButton_SetChi")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.PopupChi)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(45, 45, 91, 28))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.plainTextEdit_5.setFont(font)
        self.plainTextEdit_5.setStyleSheet("border-radius: 10;\n"
"background-color: white;\n"
"border: 1px solid gray;\n"
"padding-left: 8")
        self.plainTextEdit_5.setPlainText("")
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.label_total = QtWidgets.QLabel(self.frame_thuchi)
        self.label_total.setGeometry(QtCore.QRect(130, 10, 371, 31))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(12)
        font.setBold(True)
        self.label_total.setFont(font)
        self.label_total.setStyleSheet("#label_total{\n"
"    background-color: #EEEEEE;\n"
"    border-radius: 10;\n"
"    border: 1px solid white;\n"
"    color: #3085C3\n"
"}")
        self.label_total.setAlignment(QtCore.Qt.AlignCenter)
        self.label_total.setObjectName("label_total")
        self.label_3 = QtWidgets.QLabel(self.frame_thuchi)
        self.label_3.setGeometry(QtCore.QRect(55, 10, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #3085C3")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_thuchi)
        self.label_4.setGeometry(QtCore.QRect(10, 5, 40, 40))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/Icon/Image/manager.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_thuchi)
        self.label_5.setGeometry(QtCore.QRect(530, 60, 28, 28))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/Icon/Image/icons8-revenue-48.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.pushButton_Excel = QtWidgets.QPushButton(self.frame_thuchi)
        self.pushButton_Excel.setGeometry(QtCore.QRect(530, 10, 31, 31))
        self.pushButton_Excel.setStyleSheet("#pushButton_Excel\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"#pushButton_Excel::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_Excel::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}")
        self.pushButton_Excel.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Icon/Image/icons8-excel-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Excel.setIcon(icon10)
        self.pushButton_Excel.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Excel.setObjectName("pushButton_Excel")
        self.pushButton_hide = QtWidgets.QPushButton(self.frame_thuchi)
        self.pushButton_hide.setGeometry(QtCore.QRect(490, 27, 21, 20))
        self.pushButton_hide.setStyleSheet("#pushButton_hide\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"#pushButton_hide::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_hide::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}")
        self.pushButton_hide.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Icon/Image/icons8-eye-15.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_hide.setIcon(icon11)
        self.pushButton_hide.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_hide.setObjectName("pushButton_hide")
        self.frame_plan_note = QtWidgets.QFrame(self.frame)
        self.frame_plan_note.setGeometry(QtCore.QRect(150, 370, 551, 371))
        self.frame_plan_note.setStyleSheet("#frame_plan_note{\n"
"    background-color: white;\n"
"    border-radius: 15;\n"
"    border: 1px solid white;\n"
"}")
        self.frame_plan_note.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_plan_note.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_plan_note.setObjectName("frame_plan_note")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_plan_note)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_plan = QtWidgets.QFrame(self.frame_plan_note)
        self.frame_plan.setStyleSheet("#frame_plan{\n"
"    background-color: #B5CB99;\n"
"    border-radius: 15;\n"
"    border: 1px solid white;\n"
"}")
        self.frame_plan.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_plan.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_plan.setObjectName("frame_plan")
        self.label_8 = QtWidgets.QLabel(self.frame_plan)
        self.label_8.setGeometry(QtCore.QRect(5, 0, 31, 31))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/Icon/Image/icons8-plan-30.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.frame_plan)
        self.frame_note = QtWidgets.QFrame(self.frame_plan_note)
        self.frame_note.setStyleSheet("#frame_note{\n"
"    background-color: #F8F6F4;\n"
"    border-radius: 15;\n"
"    border: 1px solid white;\n"
"}")
        self.frame_note.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_note.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_note.setObjectName("frame_note")
        self.label_7 = QtWidgets.QLabel(self.frame_note)
        self.label_7.setGeometry(QtCore.QRect(5, 5, 25, 25))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/Icon/Image/icons8-note-30.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.frame_note)
        self.pushButton_back = QtWidgets.QPushButton(self.frame)
        self.pushButton_back.setGeometry(QtCore.QRect(150, 170, 30, 30))
        self.pushButton_back.setStyleSheet("#pushButton_back\n"
"{\n"
"    background-color: white ;\n"
"    border-radius: 15;\n"
"}\n"
"#pushButton_back:pressed\n"
"{\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_back:hover\n"
"{\n"
"    background-color: #CCFFFF;\n"
"    border-style: inset;\n"
"}")
        self.pushButton_back.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Icon/Image/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_back.setIcon(icon12)
        self.pushButton_back.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_next = QtWidgets.QPushButton(self.frame)
        self.pushButton_next.setGeometry(QtCore.QRect(670, 170, 30, 30))
        self.pushButton_next.setStyleSheet("#pushButton_next\n"
"{\n"
"    background-color :white ;\n"
"    border-radius: 15;\n"
"}\n"
"#pushButton_next:pressed\n"
"{\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_next:hover\n"
"{\n"
"    background-color: #CCFFFF;\n"
"    border-style: inset;\n"
"}")
        self.pushButton_next.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/Icon/Image/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next.setIcon(icon13)
        self.pushButton_next.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_next.setObjectName("pushButton_next")
        self.frame_Image.raise_()
        self.frame_usual_app.raise_()
        self.frame_thuchi.raise_()
        self.frame_plan_note.raise_()
        self.pushButton_back.raise_()
        self.pushButton_next.raise_()
        self.frameUart = QtWidgets.QFrame(self.centralwidget)
        self.frameUart.setGeometry(QtCore.QRect(190, 420, 211, 181))
        self.frameUart.setStyleSheet("#frameUart{\n"
"    background-color: #EDE4E0;\n"
"    border-radius: 15;\n"
"    border: 2px solid white;\n"
"}")
        self.frameUart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameUart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameUart.setObjectName("frameUart")
        self.pushButton_connectUart = QtWidgets.QPushButton(self.frameUart)
        self.pushButton_connectUart.setGeometry(QtCore.QRect(60, 150, 91, 25))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton_connectUart.setFont(font)
        self.pushButton_connectUart.setStyleSheet("#pushButton_connectUart\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"#pushButton_connectUart::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_connectUart::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}")
        self.pushButton_connectUart.setIcon(icon9)
        self.pushButton_connectUart.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_connectUart.setObjectName("pushButton_connectUart")
        self.layoutWidget = QtWidgets.QWidget(self.frameUart)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 194, 133))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_date_selected_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(11)
        font.setBold(True)
        self.label_date_selected_3.setFont(font)
        self.label_date_selected_3.setStyleSheet("#label_date_selected{\n"
"    background-color: white;\n"
"    border-radius: 10;\n"
"    border: 1px solid white;\n"
"    color: black\n"
"}")
        self.label_date_selected_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date_selected_3.setObjectName("label_date_selected_3")
        self.verticalLayout.addWidget(self.label_date_selected_3)
        self.label_date_selected_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(11)
        font.setBold(True)
        self.label_date_selected_4.setFont(font)
        self.label_date_selected_4.setStyleSheet("#label_date_selected{\n"
"    background-color: white;\n"
"    border-radius: 10;\n"
"    border: 1px solid white;\n"
"    color: black\n"
"}")
        self.label_date_selected_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date_selected_4.setObjectName("label_date_selected_4")
        self.verticalLayout.addWidget(self.label_date_selected_4)
        self.label_date_selected_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(11)
        font.setBold(True)
        self.label_date_selected_5.setFont(font)
        self.label_date_selected_5.setStyleSheet("#label_date_selected{\n"
"    background-color: white;\n"
"    border-radius: 10;\n"
"    border: 1px solid white;\n"
"    color: black\n"
"}")
        self.label_date_selected_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date_selected_5.setObjectName("label_date_selected_5")
        self.verticalLayout.addWidget(self.label_date_selected_5)
        self.label_date_selected_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(11)
        font.setBold(True)
        self.label_date_selected_6.setFont(font)
        self.label_date_selected_6.setStyleSheet("#label_date_selected{\n"
"    background-color: white;\n"
"    border-radius: 10;\n"
"    border: 1px solid white;\n"
"    color: black\n"
"}")
        self.label_date_selected_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date_selected_6.setObjectName("label_date_selected_6")
        self.verticalLayout.addWidget(self.label_date_selected_6)
        self.label_date_selected_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(11)
        font.setBold(True)
        self.label_date_selected_7.setFont(font)
        self.label_date_selected_7.setStyleSheet("#label_date_selected{\n"
"    background-color: white;\n"
"    border-radius: 10;\n"
"    border: 1px solid white;\n"
"    color: black\n"
"}")
        self.label_date_selected_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date_selected_7.setObjectName("label_date_selected_7")
        self.verticalLayout.addWidget(self.label_date_selected_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(False)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_3.setAutoFillBackground(False)
        self.comboBox_3.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    min-width: 6em;\n"
"    padding-left: 10;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background: transparent;\n"
"    border: 1px solid gray;\n"
"    padding: 4px 4px 4px 4px\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    image: url(\":/Icon/Image/icons8-down-25.png\");\n"
"    width:20;\n"
"    padding-left: 5\n"
"}\n"
"")
        self.comboBox_3.setEditable(False)
        self.comboBox_3.setMaxVisibleItems(10)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_3)
        self.comboBox_Baudrate = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(False)
        self.comboBox_Baudrate.setFont(font)
        self.comboBox_Baudrate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_Baudrate.setAutoFillBackground(False)
        self.comboBox_Baudrate.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    min-width: 6em;\n"
"    padding-left: 10;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background: transparent;\n"
"    border: 1px solid gray;\n"
"    padding: 4px 4px 4px 4px\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    image: url(\":/Icon/Image/icons8-down-25.png\");\n"
"    width:20;\n"
"    padding-left: 5\n"
"}\n"
"")
        self.comboBox_Baudrate.setEditable(False)
        self.comboBox_Baudrate.setMaxVisibleItems(10)
        self.comboBox_Baudrate.setObjectName("comboBox_Baudrate")
        self.comboBox_Baudrate.addItem("")
        self.comboBox_Baudrate.addItem("")
        self.comboBox_Baudrate.addItem("")
        self.comboBox_Baudrate.addItem("")
        self.comboBox_Baudrate.addItem("")
        self.comboBox_Baudrate.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_Baudrate)
        self.comboBox_Baudrate_2 = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(False)
        self.comboBox_Baudrate_2.setFont(font)
        self.comboBox_Baudrate_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_Baudrate_2.setAutoFillBackground(False)
        self.comboBox_Baudrate_2.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    min-width: 6em;\n"
"    padding-left: 10;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background: transparent;\n"
"    border: 1px solid gray;\n"
"    padding: 4px 4px 4px 4px\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    image: url(\":/Icon/Image/icons8-down-25.png\");\n"
"    width:20;\n"
"    padding-left: 5\n"
"}\n"
"")
        self.comboBox_Baudrate_2.setEditable(False)
        self.comboBox_Baudrate_2.setMaxVisibleItems(10)
        self.comboBox_Baudrate_2.setObjectName("comboBox_Baudrate_2")
        self.comboBox_Baudrate_2.addItem("")
        self.comboBox_Baudrate_2.addItem("")
        self.comboBox_Baudrate_2.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_Baudrate_2)
        self.comboBox_Baudrate_3 = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(False)
        self.comboBox_Baudrate_3.setFont(font)
        self.comboBox_Baudrate_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_Baudrate_3.setAutoFillBackground(False)
        self.comboBox_Baudrate_3.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    min-width: 6em;\n"
"    padding-left: 10;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background: transparent;\n"
"    border: 1px solid gray;\n"
"    padding: 4px 4px 4px 4px\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    image: url(\":/Icon/Image/icons8-down-25.png\");\n"
"    width:20;\n"
"    padding-left: 5\n"
"}\n"
"")
        self.comboBox_Baudrate_3.setEditable(False)
        self.comboBox_Baudrate_3.setMaxVisibleItems(10)
        self.comboBox_Baudrate_3.setObjectName("comboBox_Baudrate_3")
        self.comboBox_Baudrate_3.addItem("")
        self.comboBox_Baudrate_3.addItem("")
        self.comboBox_Baudrate_3.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_Baudrate_3)
        self.comboBox_Baudrate_4 = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(False)
        self.comboBox_Baudrate_4.setFont(font)
        self.comboBox_Baudrate_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_Baudrate_4.setAutoFillBackground(False)
        self.comboBox_Baudrate_4.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    min-width: 6em;\n"
"    padding-left: 10;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background: transparent;\n"
"    border: 1px solid gray;\n"
"    padding: 4px 4px 4px 4px\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    image: url(\":/Icon/Image/icons8-down-25.png\");\n"
"    width:20;\n"
"    padding-left: 5\n"
"}\n"
"")
        self.comboBox_Baudrate_4.setEditable(False)
        self.comboBox_Baudrate_4.setMaxVisibleItems(10)
        self.comboBox_Baudrate_4.setObjectName("comboBox_Baudrate_4")
        self.comboBox_Baudrate_4.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_Baudrate_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        MyApp.setCentralWidget(self.centralwidget)

        self.retranslateUi(MyApp)
        self.comboBox.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(0)
        self.comboBox_3.setCurrentIndex(0)
        self.comboBox_Baudrate.setCurrentIndex(0)
        self.comboBox_Baudrate_2.setCurrentIndex(0)
        self.comboBox_Baudrate_3.setCurrentIndex(0)
        self.comboBox_Baudrate_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MyApp)

    def retranslateUi(self, MyApp):
        _translate = QtCore.QCoreApplication.translate
        MyApp.setWindowTitle(_translate("MyApp", "MyApp"))
        self.label_10.setText(_translate("MyApp", "Đình\n"
" Thuận"))
        self.pushButton_Plus_pass.setText(_translate("MyApp", "+"))
        self.label_time.setText(_translate("MyApp", "23:05"))
        self.label_thu.setText(_translate("MyApp", "Friday"))
        self.label_day.setText(_translate("MyApp", "30"))
        self.pushButton_Plus_thu.setText(_translate("MyApp", "+"))
        self.label_total_thu.setText(_translate("MyApp", "Tổng: 10 000 000 VNĐ"))
        self.comboBox.setItemText(0, _translate("MyApp", "Lương tháng"))
        self.comboBox.setItemText(1, _translate("MyApp", "Khác"))
        self.label.setText(_translate("MyApp", "VNĐ"))
        self.pushButton_SetThu.setText(_translate("MyApp", "Enter"))
        self.pushButton_Plus_chi.setText(_translate("MyApp", "-"))
        self.label_total_chi.setText(_translate("MyApp", "Tổng: 10 000 000 VNĐ"))
        self.comboBox_2.setItemText(0, _translate("MyApp", "Tiền trọ"))
        self.comboBox_2.setItemText(1, _translate("MyApp", "Sinh hoạt"))
        self.comboBox_2.setItemText(2, _translate("MyApp", "Đi chơi"))
        self.comboBox_2.setItemText(3, _translate("MyApp", "Ăn uống"))
        self.comboBox_2.setItemText(4, _translate("MyApp", "Khác"))
        self.label_2.setText(_translate("MyApp", "VNĐ"))
        self.pushButton_SetChi.setText(_translate("MyApp", "Enter"))
        self.label_total.setText(_translate("MyApp", "Tổng tích lũy: *** *** *** VNĐ"))
        self.label_3.setText(_translate("MyApp", "Quản lý \n"
"thu chi"))
        self.pushButton_connectUart.setText(_translate("MyApp", "Connect"))
        self.label_date_selected_3.setText(_translate("MyApp", "Port"))
        self.label_date_selected_4.setText(_translate("MyApp", "Baud rate"))
        self.label_date_selected_5.setText(_translate("MyApp", "Parity Bit"))
        self.label_date_selected_6.setText(_translate("MyApp", "Stop bit"))
        self.label_date_selected_7.setText(_translate("MyApp", "Data bit"))
        self.comboBox_3.setItemText(0, _translate("MyApp", "COM 1"))
        self.comboBox_Baudrate.setItemText(0, _translate("MyApp", "4800"))
        self.comboBox_Baudrate.setItemText(1, _translate("MyApp", "8600"))
        self.comboBox_Baudrate.setItemText(2, _translate("MyApp", "19200"))
        self.comboBox_Baudrate.setItemText(3, _translate("MyApp", "38400"))
        self.comboBox_Baudrate.setItemText(4, _translate("MyApp", "115200"))
        self.comboBox_Baudrate.setItemText(5, _translate("MyApp", "921600"))
        self.comboBox_Baudrate_2.setItemText(0, _translate("MyApp", "No Parity"))
        self.comboBox_Baudrate_2.setItemText(1, _translate("MyApp", "Odd Parity"))
        self.comboBox_Baudrate_2.setItemText(2, _translate("MyApp", "Even Parity"))
        self.comboBox_Baudrate_3.setItemText(0, _translate("MyApp", "1 Bit"))
        self.comboBox_Baudrate_3.setItemText(1, _translate("MyApp", "1.5 Bits"))
        self.comboBox_Baudrate_3.setItemText(2, _translate("MyApp", "2 Bits"))
        self.comboBox_Baudrate_4.setItemText(0, _translate("MyApp", "5"))
import ResourceFile_rc
