# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\LearningCode\Git code\SelfLearning\Personal projects\MyApp\popup_thu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_popup_Thu(object):
    def setupUi(self, popup_Thu):
        popup_Thu.setObjectName("popup_Thu")
        popup_Thu.resize(425, 203)
        self.frametest = QtWidgets.QFrame(popup_Thu)
        self.frametest.setGeometry(QtCore.QRect(0, 0, 201, 181))
        self.frametest.setStyleSheet("#frametest{\n"
"    background-color: #EDE4E0;\n"
"    border-radius: 15;\n"
"    border: 2px solid white;\n"
"}")
        self.frametest.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frametest.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frametest.setObjectName("frametest")
        self.comboBox = QtWidgets.QComboBox(self.frametest)
        self.comboBox.setGeometry(QtCore.QRect(45, 48, 141, 28))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.comboBox.setFont(font)
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    min-width: 6em;\n"
"    padding-left: 10;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background: transparent;\n"
"    border: 1px solid gray;\n"
"    padding: 4px 4px 4px 4px\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    image: url(\":/Icon/Image/icons8-down-25.png\");\n"
"    width:20;\n"
"    padding-left: 5\n"
"}\n"
"")
        self.comboBox.setEditable(False)
        self.comboBox.setMaxVisibleItems(10)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.frametest)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(45, 118, 141, 28))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setBold(True)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setStyleSheet("border-radius: 10;\n"
"background-color: white;\n"
"border: 1px solid gray;\n"
"padding-left: 5")
        self.plainTextEdit_2.setPlainText("")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_11 = QtWidgets.QLabel(self.frametest)
        self.label_11.setGeometry(QtCore.QRect(10, 48, 25, 25))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/Icon/Image/icons8-goal-40.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frametest)
        self.label_12.setGeometry(QtCore.QRect(10, 83, 25, 25))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/Icon/Image/icons8-money-40.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frametest)
        self.label_13.setGeometry(QtCore.QRect(10, 118, 25, 25))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/Icon/Image/icons8-note-40.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label = QtWidgets.QLabel(self.frametest)
        self.label.setGeometry(QtCore.QRect(150, 83, 35, 20))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_SetThu = QtWidgets.QPushButton(self.frametest)
        self.pushButton_SetThu.setGeometry(QtCore.QRect(60, 151, 71, 25))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton_SetThu.setFont(font)
        self.pushButton_SetThu.setStyleSheet("#pushButton_SetThu\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"#pushButton_SetThu::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_SetThu::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/Image/icons8-next-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_SetThu.setIcon(icon)
        self.pushButton_SetThu.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_SetThu.setObjectName("pushButton_SetThu")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.frametest)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(45, 83, 101, 28))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setTabletTracking(False)
        self.plainTextEdit_3.setAcceptDrops(True)
        self.plainTextEdit_3.setWhatsThis("")
        self.plainTextEdit_3.setAutoFillBackground(False)
        self.plainTextEdit_3.setStyleSheet("border-radius: 10;\n"
"background-color: white;\n"
"border: 1px solid gray;\n"
"padding-left: 8")
        self.plainTextEdit_3.setTabChangesFocus(False)
        self.plainTextEdit_3.setReadOnly(False)
        self.plainTextEdit_3.setPlainText("")
        self.plainTextEdit_3.setOverwriteMode(False)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.label_date_selected_2 = QtWidgets.QLabel(self.frametest)
        self.label_date_selected_2.setGeometry(QtCore.QRect(60, 13, 91, 25))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.label_date_selected_2.setFont(font)
        self.label_date_selected_2.setStyleSheet("#label_date_selected{\n"
"    background-color: white;\n"
"    border-radius: 10;\n"
"    border: 1px solid white;\n"
"    color: black\n"
"}")
        self.label_date_selected_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date_selected_2.setObjectName("label_date_selected_2")
        self.plainTextEdit_7 = QtWidgets.QPlainTextEdit(self.frametest)
        self.plainTextEdit_7.setGeometry(QtCore.QRect(45, 13, 141, 28))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setBold(True)
        self.plainTextEdit_7.setFont(font)
        self.plainTextEdit_7.setStyleSheet("border-radius: 10;\n"
"background-color: white;\n"
"border: 1px solid gray;\n"
"padding-left: 5")
        self.plainTextEdit_7.setPlainText("")
        self.plainTextEdit_7.setObjectName("plainTextEdit_7")
        self.label_18 = QtWidgets.QLabel(self.frametest)
        self.label_18.setGeometry(QtCore.QRect(8, 13, 31, 31))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(":/Icon/Image/icons8-calendar-48.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.pushButton_Selectday_Thu = QtWidgets.QPushButton(self.frametest)
        self.pushButton_Selectday_Thu.setGeometry(QtCore.QRect(160, 15, 21, 24))
        self.pushButton_Selectday_Thu.setStyleSheet("#pushButton_Selectday_Thu\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"#pushButton_Selectday_Thu::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_Selectday_Thu::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}")
        self.pushButton_Selectday_Thu.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icon/Image/icons8-calendar-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Selectday_Thu.setIcon(icon1)
        self.pushButton_Selectday_Thu.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_Selectday_Thu.setObjectName("pushButton_Selectday_Thu")
        self.label_date_selected_Thu = QtWidgets.QLabel(self.frametest)
        self.label_date_selected_Thu.setGeometry(QtCore.QRect(60, 15, 91, 25))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.label_date_selected_Thu.setFont(font)
        self.label_date_selected_Thu.setStyleSheet("#label_date_selected_Thu{\n"
"    background-color: white;\n"
"    border-radius: 10;\n"
"    border: 1px solid white;\n"
"    color: black\n"
"}")
        self.label_date_selected_Thu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date_selected_Thu.setObjectName("label_date_selected_Thu")
        self.PopupselectDay_Thu = QtWidgets.QFrame(popup_Thu)
        self.PopupselectDay_Thu.setGeometry(QtCore.QRect(210, 30, 191, 71))
        self.PopupselectDay_Thu.setStyleSheet("#PopupselectDay_Thu{\n"
"    background-color: white;\n"
"    border-radius: 15;\n"
"    border: 2px solid white;\n"
"}")
        self.PopupselectDay_Thu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PopupselectDay_Thu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PopupselectDay_Thu.setObjectName("PopupselectDay_Thu")
        self.label_21 = QtWidgets.QLabel(self.PopupselectDay_Thu)
        self.label_21.setGeometry(QtCore.QRect(40, 37, 31, 31))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap(":/Icon/Image/icons8-calendar-48.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.pushButton_SelectedDay_Thu = QtWidgets.QPushButton(self.PopupselectDay_Thu)
        self.pushButton_SelectedDay_Thu.setGeometry(QtCore.QRect(70, 40, 71, 25))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton_SelectedDay_Thu.setFont(font)
        self.pushButton_SelectedDay_Thu.setStyleSheet("#pushButton_SelectedDay_Thu\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"#pushButton_SelectedDay_Thu::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_SelectedDay_Thu::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}")
        self.pushButton_SelectedDay_Thu.setIcon(icon)
        self.pushButton_SelectedDay_Thu.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_SelectedDay_Thu.setObjectName("pushButton_SelectedDay_Thu")
        self.pushButton_back_day_Thu = QtWidgets.QPushButton(self.PopupselectDay_Thu)
        self.pushButton_back_day_Thu.setGeometry(QtCore.QRect(0, 10, 30, 30))
        self.pushButton_back_day_Thu.setStyleSheet("#pushButton_back_day_Thu\n"
"{\n"
"    background-color: white ;\n"
"    border-radius: 15;\n"
"}\n"
"#pushButton_back_day_Thu:pressed\n"
"{\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_back_day_Thu:hover\n"
"{\n"
"    background-color: #CCFFFF;\n"
"    border-style: inset;\n"
"}")
        self.pushButton_back_day_Thu.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icon/Image/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_back_day_Thu.setIcon(icon2)
        self.pushButton_back_day_Thu.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_back_day_Thu.setObjectName("pushButton_back_day_Thu")
        self.pushButton_next_day_Thu = QtWidgets.QPushButton(self.PopupselectDay_Thu)
        self.pushButton_next_day_Thu.setGeometry(QtCore.QRect(160, 10, 30, 30))
        self.pushButton_next_day_Thu.setStyleSheet("#pushButton_next_day_Thu\n"
"{\n"
"    background-color :white ;\n"
"    border-radius: 15;\n"
"}\n"
"#pushButton_next_day_Thu:pressed\n"
"{\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_next_day_Thu:hover\n"
"{\n"
"    background-color: #CCFFFF;\n"
"    border-style: inset;\n"
"}")
        self.pushButton_next_day_Thu.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icon/Image/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next_day_Thu.setIcon(icon3)
        self.pushButton_next_day_Thu.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_next_day_Thu.setObjectName("pushButton_next_day_Thu")
        self.label_date_select_Thu = QtWidgets.QLabel(self.PopupselectDay_Thu)
        self.label_date_select_Thu.setGeometry(QtCore.QRect(30, 10, 131, 25))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.label_date_select_Thu.setFont(font)
        self.label_date_select_Thu.setStyleSheet("#label_date_select_Thu{\n"
"    background-color: white;\n"
"    border-radius: 10;\n"
"    border: 1px solid gray;\n"
"    color: black\n"
"}")
        self.label_date_select_Thu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date_select_Thu.setObjectName("label_date_select_Thu")

        self.retranslateUi(popup_Thu)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(popup_Thu)

    def retranslateUi(self, popup_Thu):
        _translate = QtCore.QCoreApplication.translate
        popup_Thu.setWindowTitle(_translate("popup_Thu", "Dialog"))
        self.comboBox.setItemText(0, _translate("popup_Thu", "Lương tháng"))
        self.comboBox.setItemText(1, _translate("popup_Thu", "Khác"))
        self.label.setText(_translate("popup_Thu", "VNĐ"))
        self.pushButton_SetThu.setText(_translate("popup_Thu", "Enter"))
        self.label_date_selected_2.setText(_translate("popup_Thu", "09/12/2023"))
        self.label_date_selected_Thu.setText(_translate("popup_Thu", "09/12/2023"))
        self.pushButton_SelectedDay_Thu.setText(_translate("popup_Thu", "Enter"))
        self.label_date_select_Thu.setText(_translate("popup_Thu", "09/12/2023"))
import ResourceFile_rc
